name: Formatter

on:
  push:
    branches:
      -master
  pull_request:

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade yapf
          echo $(yapf --version)
      - name: Format with YAPF
        run: |
          yapf --verbose --recursive --in-place --parallel --style '{SPACES_AROUND_POWER_OPERATOR: True}' .
      - name: Push commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automation: Formatter" --all | exit 0
          git push
